"""empty message

Revision ID: 7bafb22a41ff
Revises: cbf576d381e5
Create Date: 2019-09-17 16:42:45.119172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bafb22a41ff'
down_revision = 'cbf576d381e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('excerpt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'score', 'excerpt', ['excerpt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'excerpt_id')
    # ### end Alembic commands ###
